name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle


    - name: Run Lint With Gradile
      run: ./gradlew lintDebug

    - name: Uploade Report Test 
      uses: actions/artifact@v2
      with:
        name: index.html
        path: app/build/reports/lint-results-release.html
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run a one-line script
      run: echo Hello,World
